version: "3"

services:
  postgres-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass123
  mongodb:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-course
